CALL "ArithmeticCodeCodec" "-c" "empty.txt" "empty.acf"
CALL "ArithmeticCodeCodec" "-d" "empty.acf" "empty.out.txt"
CALL "FC" "empty.txt" "empty.out.txt"
CALL "ArithmeticCodeCodec" "-c" "one.txt" "one.acf"
CALL "ArithmeticCodeCodec" "-d" "one.acf" "one.out.txt"
CALL "FC" "one.txt" "one.out.txt"
CALL "ArithmeticCodeCodec" "-c" "test.txt" "test.acf"
CALL "ArithmeticCodeCodec" "-d" "test.acf" "test.out.txt"
CALL "FC" "test.txt" "test.out.txt"
CALL "ArithmeticCodeCodec" "-c" "war_and_peace.txt" "war_and_peace.acf"
CALL "ArithmeticCodeCodec" "-d" "war_and_peace.acf" "war_and_peace.out.txt"
CALL "FC" "war_and_peace.txt" "war_and_peace.out.txt"
CALL "ArithmeticCodeCodec" "-c" "large.txt" "large.acf"
CALL "ArithmeticCodeCodec" "-d" "large.acf" "large.out.txt"
CALL "FC" "large.txt" "large.out.txt"
CALL "ArithmeticCodeCodec" "-c" "different.txt" "different.acf"
CALL "ArithmeticCodeCodec" "-d" "different.acf" "different.out.txt"
CALL "FC" "different.txt" "different.out.txt"
DEL "empty.acf" "empty.out.txt" "one.acf" "one.out.txt" "test.acf" "test.out.txt" "war_and_peace.acf" "war_and_peace.out.txt" "large.acf" "large.out.txt" "different.acf" "different.out.txt"
